name: Wedding BintangAyu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Project
        run: |
          npm run build

      - name: Deploy Next.js Project
        if: github.ref == 'refs/heads/main'
        run: |
          # Adjust paths based on your project setup
          BUILD_DIR=".next"

          # Deploy application files
          sshpass -p 'Seni@ti12345' rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ root@195.35.23.150:/var/www/wedding-bna-fe/